// descriptions.js - Provides descriptions for each shape

// Object containing descriptions for each shape
const shapeDescriptions = {
    // Basic Shapes
    cube: `
        <h4>Cube</h4>
        <p>A regular hexahedron with 6 square faces, 12 edges, and 8 vertices.</p>
        <p>In mathematics, a cube is a three-dimensional solid object bounded by six square faces, with three meeting at each vertex.</p>
    `,
    sphere: `
        <h4>Sphere</h4>
        <p>A perfectly round geometrical object in three-dimensional space.</p>
        <p>A sphere is defined mathematically as the set of points that are all at the same distance from a given point in three-dimensional space.</p>
    `,
    torus: `
        <h4>Torus (Donut)</h4>
        <p>A surface of revolution generated by revolving a circle in three-dimensional space about an axis that is coplanar with the circle.</p>
        <p>The torus is a classic shape in topology and can be described using parametric equations.</p>
    `,
    cylinder: `
        <h4>Cylinder</h4>
        <p>A solid geometrical figure with straight parallel sides and a circular or oval cross-section.</p>
        <p>The cylinder is one of the most basic curved solids, with applications in engineering and mathematics.</p>
    `,
    cone: `
        <h4>Cone</h4>
        <p>A solid or hollow object that tapers from a circular or roughly circular base to a point.</p>
        <p>In geometry, a cone is formed by a set of line segments, half-lines, or lines connecting a common point, the apex, to all the points on a base.</p>
    `,
    
    // Platonic Solids
    tetrahedron: `
        <h4>Tetrahedron</h4>
        <p>A polyhedron with four triangular faces, six edges, and four vertices.</p>
        <p>It is the simplest of all regular polyhedra and the only Platonic solid with four faces.</p>
    `,
    octahedron: `
        <h4>Octahedron</h4>
        <p>A polyhedron with eight triangular faces, twelve edges, and six vertices.</p>
        <p>Each vertex has four edges meeting at it, giving it a vertex figure that forms a square.</p>
    `,
    dodecahedron: `
        <h4>Dodecahedron</h4>
        <p>A polyhedron with twelve pentagonal faces, thirty edges, and twenty vertices.</p>
        <p>The regular dodecahedron has been known since ancient times and features prominently in Plato's work.</p>
    `,
    icosahedron: `
        <h4>Icosahedron</h4>
        <p>A polyhedron with twenty triangular faces, thirty edges, and twelve vertices.</p>
        <p>Each vertex of a regular icosahedron is adjacent to five other vertices, and the shape has rotational icosahedral symmetry.</p>
    `,
    
    // Mathematical Shapes
    torusKnot: `
        <h4>Torus Knot</h4>
        <p>A knot that lies on the surface of an unknotted torus in three-dimensional space.</p>
        <p>Torus knots are constructed by wrapping a circle around a torus in a helical pattern.</p>
    `,
    steinmetzSolid: `
        <h4>Steinmetz Solid</h4>
        <p>The solid common to two or three cylinders of equal radius intersecting at right angles.</p>
        <p>Named after Charles Proteus Steinmetz, it has interesting properties related to volume calculations.</p>
    `,
    mobius: `
        <h4>Möbius Strip</h4>
        <p>A surface with only one side and one boundary curve.</p>
        <p>It can be realized as a ruled surface and has the mathematical property of being non-orientable.</p>
    `,
    kleinBottle: `
        <h4>Klein Bottle</h4>
        <p>A non-orientable surface with no inside or outside.</p>
        <p>The Klein bottle is a two-dimensional manifold that cannot be properly embedded in three-dimensional space without intersecting itself.</p>
    `,
    trefoilKnot: `
        <h4>Trefoil Knot</h4>
        <p>The simplest non-trivial knot with three crossings.</p>
        <p>The trefoil is chiral, meaning that it is not equivalent to its own mirror image.</p>
    `,
    figureBight: `
        <h4>Figure-8 Knot</h4>
        <p>The unique knot with four crossings.</p>
        <p>It is achiral, meaning that it is equivalent to its mirror image, and it has mathematical connections to hyperbolic geometry.</p>
    `,
    
    // Geometric Variations
    triangularPrism: `
        <h4>Triangular Prism</h4>
        <p>A polyhedron made of a triangular base, a translated copy, and three faces joining corresponding edges.</p>
        <p>It has 5 faces, 9 edges, and 6 vertices and is used in engineering and optics.</p>
    `,
    pentagonalPrism: `
        <h4>Pentagonal Prism</h4>
        <p>A prism with a regular pentagon base.</p>
        <p>It has 7 faces, 15 edges, and 10 vertices, and is one of the Archimedean prisms.</p>
    `,
    hexagonalPrism: `
        <h4>Hexagonal Prism</h4>
        <p>A prism with a regular hexagon base.</p>
        <p>It has 8 faces, 18 edges, and 12 vertices, and is seen in natural forms like honeycomb cells and crystal structures.</p>
    `,
    star: `
        <h4>Star Polyhedron</h4>
        <p>A polyhedron with a star-like appearance, often with self-intersecting faces.</p>
        <p>Star polyhedra include the Kepler-Poinsot polyhedra and various stellations of the Platonic solids.</p>
    `,
    gyroid: `
        <h4>Gyroid Surface</h4>
        <p>A triply periodic minimal surface discovered by Alan Schoen in 1970.</p>
        <p>It has zero mean curvature and divides space into two regions that are mirror images of each other.</p>
    `,
    
    // Artistic Shapes
    horn: `
        <h4>Spiral Horn</h4>
        <p>A conical shape that twists while expanding.</p>
        <p>The geometry is inspired by natural horns found in animals like rams and antelopes.</p>
    `,
    shell: `
        <h4>Nautilus Shell</h4>
        <p>A logarithmic spiral shell modeled after the nautilus mollusk.</p>
        <p>The nautilus shell grows its shell chambers in a logarithmic spiral, creating a natural example of the golden ratio.</p>
    `,
    helix: `
        <h4>Double Helix</h4>
        <p>Two congruent helices with the same axis and handedness but offset from one another.</p>
        <p>Double helices are most famous for their occurrence in DNA structure, one of nature's most important geometries.</p>
    `,
    wave: `
        <h4>Wave Surface</h4>
        <p>A parameterized surface that resembles a propagating wave.</p>
        <p>Wave surfaces model physical phenomena such as water waves, sound waves, and electromagnetic waves.</p>
    `,
    twist: `
        <h4>Twisted Cube</h4>
        <p>A cube that has been subjected to a twisting deformation.</p>
        <p>This shape demonstrates how basic forms can be transformed using mathematical operations.</p>
    `,
    
    // Advanced Mathematical
    catenoid: `
        <h4>Catenoid</h4>
        <p>A surface formed by rotating a catenary curve around its directrix.</p>
        <p>The catenoid is a minimal surface, meaning it has zero mean curvature at every point.</p>
    `,
    helicoid: `
        <h4>Helicoid</h4>
        <p>A ruled surface that resembles a spiral staircase.</p>
        <p>The helicoid is a minimal surface that shares many mathematical properties with the catenoid.</p>
    `,
    boySurface: `
        <h4>Boy's Surface</h4>
        <p>An immersion of the real projective plane in 3D space.</p>
        <p>Discovered by Werner Boy in 1901, it has no self-intersections and is a non-orientable surface.</p>
    `,
    romanSurface: `
        <h4>Roman Surface</h4>
        <p>A self-intersecting surface discovered by Jakob Steiner.</p>
        <p>Also known as Steiner's Roman surface, it is a non-orientable surface with interesting symmetry properties.</p>
    `,
    crossCap: `
        <h4>Cross-Cap</h4>
        <p>A two-dimensional surface that is topologically equivalent to a projective plane.</p>
        <p>The cross-cap is a non-orientable surface that cannot be embedded in three-dimensional space without self-intersections.</p>
    `,
    
    // Fractals and Complex
    sierpinski: `
        <h4>Sierpinski Pyramid</h4>
        <p>A three-dimensional analogue of the Sierpinski triangle fractal.</p>
        <p>It is constructed through an iterative process of removing central tetrahedra, creating a self-similar structure with fractal dimension.</p>
    `,
    fibonacci: `
        <h4>Fibonacci Spiral</h4>
        <p>A spiral based on the Fibonacci sequence and approximating the golden spiral.</p>
        <p>This structure appears frequently in nature, from galaxies to sunflower seed arrangements.</p>
    `,
    superellipsoid: `
        <h4>Superellipsoid</h4>
        <p>A generalization of an ellipsoid with varying exponents that control its shape.</p>
        <p>Superellipsoids can represent a wide range of shapes from cubes to spheres and many forms in between.</p>
    `,
    hyperboloid: `
        <h4>Hyperboloid</h4>
        <p>A quadric surface generated by rotating a hyperbola around one of its axes.</p>
        <p>Hyperboloids are used in architecture and engineering due to their structural properties and ability to be constructed with straight lines.</p>
    `
};

// Export the object
export { shapeDescriptions };